name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main
      - dev # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13" # Set this to the Python version you use

      - name: Install dependencies
        run: |
          pip install awsebcli
          pip install -r requirements.txt

      # Deploy to onenode-env when branch is main
      - name: Deploy to AWS Elastic Beanstalk (onenode-env)
        if: github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-2"
        run: |
          eb init -p python-3.13 onenode --region $AWS_REGION
          eb use onenode-env
          eb deploy

      # Deploy to onenode-beat when branch is main
      - name: Deploy to AWS Elastic Beanstalk (onenode-beat)
        if: github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-2"
        run: |
          eb init -p python-3.13 onenode --region $AWS_REGION
          eb use onenode-beat
          eb deploy

      # Deploy to onenode-env-dev when branch is dev
      - name: Deploy to AWS Elastic Beanstalk (onenode-env-dev)
        if: github.ref == 'refs/heads/dev'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-2"
        run: |
          eb init -p python-3.13 OneNodeBrain --region $AWS_REGION
          eb use onenode-env-dev
          eb deploy
